#!/usr/bin/env bash

# do symlinks into Documents, Pictures

ln -s ~/Dropbox/Backup/Books ~/Documents
ln -s ~/Dropbox/Backup/Fonts ~/Documents
ln -s ~/Dropbox/Backup/Info ~/Documents
ln -s ~/Dropbox/Backup/Presentations ~/Documents
ln -s ~/Dropbox/Backup/Projects ~/Documents

ln -s ~/Dropbox/Text ~/Documents

ln -s ~/Dropbox/Pictures/Desktop ~/Pictures
ln -s ~/Dropbox/Pictures/Icons ~/Pictures
ln -s ~/Dropbox/Pictures/Web ~/Pictures