#!/usr/bin/env bash

echo "[Config] Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "[Config] Add passsphrase to macOS keychain"
  [[ -f ~/.ssh/id_rsa.pub ]] && /usr/bin/ssh-add -K ~/.ssh/id_rsa

echo "[Config] Copying public key to clipboard. Paste it into your Github account"
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
  open https://github.com/account/ssh

echo "[Install] Homebrew"
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  brew update

echo "[Install] Git"
  brew install git

echo "[Install] Postgres"
  brew install postgres
  brew services start postgresql

echo "[Install] Redis"
  brew install redis
  brew services start redis

echo "[Install] rcm"
  brew tap thoughtbot/formulae
  brew install rcm

echo "[User Input] Install dotfiles"
  open 'http://github.com/andycroll/dotfiles'

echo "[Install] ohmysh"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
